id: I3FD2D631
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:14:44.273063
last_modified: 2023-02-08 15:14:44.273175
source_metadata:
  title: Nirvikalpapraveśadhāraṇī
  language: bo
bases:
  9A2C:
    base_file: 9A2C.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
